// MIT License - Copyright (c) 2026 wallstop
// Full license text: https://github.com/wallstop/unity-helpers/blob/main/LICENSE

[assembly: WallstopStudios.UnityHelpers.Core.Serialization.WallstopProto.WProtoSurrogate(
    typeof(WallstopStudios.UnityHelpers.Tests.Serialization.SchemaForeignVector),
    typeof(WallstopStudios.UnityHelpers.Tests.Serialization.SchemaForeignVectorSurrogate)
)]

namespace WallstopStudios.UnityHelpers.Tests.Serialization
{
    using System;
    using System.Collections.Generic;
    using NUnit.Framework;
    using WallstopStudios.UnityHelpers.Core.Serialization.WallstopProto;

    /// <summary>
    /// Pins the proto3 schema text against the wire shapes the formatters actually write.
    /// </summary>
    public sealed class WProtoSchemaTextTests
    {
        private const string GeneratedHeader =
            "// Generated by Wallstop Studios Unity Helpers. Do not edit; regenerate instead.\n"
            + "syntax = \"proto3\";\n";

        [Test]
        public void SimpleContractRendersTheFullSchemaText()
        {
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaPoint) },
                "test.pkg",
                null,
                out string schema,
                out IReadOnlyList<string> diagnostics
            );

            Assert.IsTrue(rendered, "A contract type must render.");
            Assert.AreEqual(
                GeneratedHeader
                    + "package test.pkg;\n"
                    + "\n"
                    + "message SchemaPoint {\n"
                    + "  int32 X = 1;\n"
                    + "  int32 Y = 2;\n"
                    + "}\n"
                    + "\n",
                schema,
                "The schema is generated output; its exact text is the contract."
            );
            Assert.IsEmpty(diagnostics, "A fully supported contract must not report anything.");
        }

        [Test]
        public void ReservedNumbersAndNamesReachTheSchema()
        {
            // Without these the exported schema permits, in the consumer's own toolchain, exactly
            // the reuse the generator refuses here (#608) -- so a removed member's number would come
            // back meaning something else one build system over.
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaReserved) },
                "test.pkg",
                null,
                out string schema,
                out IReadOnlyList<string> diagnostics
            );

            Assert.IsTrue(rendered);
            Assert.AreEqual(
                GeneratedHeader
                    + "package test.pkg;\n"
                    + "\n"
                    + "message SchemaReserved {\n"
                    + "  reserved 2, 7;\n"
                    + "  reserved \"Armour\", \"Health\";\n"
                    + "  int32 Kept = 1;\n"
                    + "}\n"
                    + "\n",
                schema,
                "The schema is generated output; its exact text is the contract."
            );
            Assert.IsEmpty(diagnostics);
        }

        /// <summary>
        /// An enum's reservations reach the schema the way a message's do.
        /// </summary>
        /// <remarks>
        /// The value range is the difference, and it is why this is not the same code path with a
        /// different block name: a field number starts at 1, an enum value is any int32, and
        /// filtering an enum through the message range would silently drop a reservation of 0 --
        /// the value proto3 most wants pinned (#609).
        /// </remarks>
        [Test]
        public void ReservedEnumValuesAndNamesReachTheSchema()
        {
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaReservedEnumHost) },
                "test.pkg",
                null,
                out string schema,
                out IReadOnlyList<string> diagnostics
            );

            Assert.IsTrue(rendered);
            StringAssert.Contains(
                "enum SchemaReservedEnum {\n"
                    + "  reserved -2, 0, 3;\n"
                    + "  reserved \"Poisoned\";\n"
                    + "  Unspecified = 1;\n"
                    + "  Burning = 2;\n"
                    + "}",
                schema,
                "the schema is generated output; its exact text is the contract"
            );
            CollectionAssert.AreEqual(
                new[]
                {
                    "enum SchemaReservedEnum: proto3 wants the first member at 0; it opens at 1.",
                },
                diagnostics,
                "reserving 0 is exactly why this enum cannot open at it, and that stays reported"
            );
        }

        [Test]
        public void AReservedNumberProtocCouldNotParseIsOmittedAndReported()
        {
            // protoc rejects both ends of the field-number range and owns 19000-19999 itself, so
            // emitting one would make the whole file impossible to parse -- a schema nobody can read is
            // worse than one missing a reservation, and the diagnostic says which was dropped.
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaReservedOutOfRange) },
                "test.pkg",
                null,
                out string schema,
                out IReadOnlyList<string> diagnostics
            );

            Assert.IsTrue(rendered);
            StringAssert.DoesNotContain("reserved", schema);
            CollectionAssert.AreEqual(
                new[]
                {
                    "SchemaReservedOutOfRange: reserved field number 0 is outside the range proto3 allows; omitted.",
                    "SchemaReservedOutOfRange: reserved field number 19500 is outside the range proto3 allows; omitted.",
                    "SchemaReservedOutOfRange: reserved field number 536870912 is outside the range proto3 allows; omitted.",
                },
                diagnostics,
                "each dropped number has to be named, or the author cannot tell which record was lost"
            );
        }

        [Test]
        public void ScalarMembersMapToTheirWireTypes()
        {
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaScalars) },
                null,
                null,
                out string schema,
                out IReadOnlyList<string> _
            );

            Assert.IsTrue(rendered);
            StringAssert.Contains(
                "sint64 ZigZagValue = 1;",
                schema,
                "DataFormat.ZigZag renders sint."
            );
            StringAssert.Contains("int32 Signed = 2;", schema);
            StringAssert.Contains("uint32 Unsigned = 3;", schema);
            StringAssert.Contains("fixed64 DoubleValue = 4;", schema);
            StringAssert.Contains("fixed32 FloatValue = 5;", schema);
            StringAssert.Contains("string Name = 6;", schema);
            StringAssert.Contains(
                "bytes Payload = 7;",
                schema,
                "A byte[] member is bytes, not a run."
            );
            StringAssert.Contains("uint32 Initial = 8;", schema, "A char member rides a varint.");
            StringAssert.Contains("bool Flag = 9;", schema);
            StringAssert.Contains(
                "optional int32 Maybe = 10;",
                schema,
                "Nullable presence is explicit."
            );
        }

        [Test]
        public void BclValueMembersRenderAsTheirMessageShapes()
        {
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaBcl) },
                null,
                null,
                out string schema,
                out IReadOnlyList<string> _
            );

            Assert.IsTrue(rendered);
            StringAssert.Contains("BclGuid Id = 1;", schema);
            StringAssert.Contains("BclDateTime Moment = 2;", schema);
            StringAssert.Contains("BclTimeSpan Duration = 3;", schema);
            StringAssert.Contains("BclDecimal Amount = 4;", schema);
            StringAssert.Contains("BclUri Source = 5;", schema);
            StringAssert.Contains(
                "message BclGuid {\n  fixed64 low = 1;\n  fixed64 high = 2;\n}",
                schema
            );
            StringAssert.Contains(
                "message BclDateTime {\n  sint64 value = 1;\n  uint32 scale = 2;\n}",
                schema
            );
        }

        [Test]
        public void CollectionShapesMatchTheGeneratorWrappers()
        {
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaCollections) },
                null,
                null,
                out string schema,
                out IReadOnlyList<string> _
            );

            Assert.IsTrue(rendered);
            StringAssert.Contains(
                "message RowsEntry {\n  repeated int32 values = 1;\n}",
                schema,
                "A jagged array becomes the wrapper message the generator synthesizes."
            );
            StringAssert.Contains("repeated RowsEntry Rows = 1;", schema);
            StringAssert.Contains(
                "repeated bytes Blobs = 2;",
                schema,
                "byte[][] is repeated bytes, not a wrapper."
            );
            StringAssert.Contains(
                "message GridRect {\n  repeated int32 dims = 1;\n  repeated int32 values = 2;\n}",
                schema,
                "A rectangular array becomes the dims/values wrapper."
            );
            StringAssert.Contains("GridRect Grid = 3;", schema);
            StringAssert.Contains("map<string, int32> Counts = 4;", schema);
            StringAssert.Contains("repeated SchemaPoint Points = 5;", schema);
        }

        [Test]
        public void JaggedOfRectangularRepeatsTheDimsValuesWrapperDirectly()
        {
            // int[][,] is a run whose element is a rectangular array: the outer run is the member's
            // repeated field, and the inner rectangular level gets the dims/values wrapper -- the
            // same one shape the generator synthesizes for a top-level int[,].
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaJaggedOfRectangular) },
                null,
                null,
                out string schema,
                out IReadOnlyList<string> diagnostics
            );

            Assert.IsTrue(rendered);
            StringAssert.Contains(
                "message RectsRect {\n  repeated int32 dims = 1;\n  repeated int32 values = 2;\n}",
                schema,
                "The inner rectangular level carries its dimensions."
            );
            StringAssert.Contains(
                "repeated RectsRect Rects = 1;",
                schema,
                "The outer run references the rectangular wrapper directly."
            );
            Assert.IsEmpty(diagnostics);
        }

        [Test]
        public void SurrogatesSubstituteBeforeAnyOtherMapping()
        {
            Dictionary<Type, Type> surrogates = new Dictionary<Type, Type>
            {
                { typeof(SchemaForeignVector), typeof(SchemaForeignVectorSurrogate) },
            };

            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaSurrogateHost) },
                null,
                surrogates,
                out string schema,
                out IReadOnlyList<string> diagnostics
            );

            Assert.IsTrue(rendered);
            StringAssert.Contains(
                "SchemaForeignVectorSurrogate Position = 1;",
                schema,
                "The surrogate's message is the field's type, as the wire has it."
            );
            Assert.IsEmpty(diagnostics);
        }

        [Test]
        public void NameCollisionsAreRenamedWithADiagnostic()
        {
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaPoint), typeof(SchemaPointAlias) },
                null,
                null,
                out string schema,
                out IReadOnlyList<string> diagnostics
            );

            Assert.IsTrue(rendered);
            StringAssert.Contains("message SchemaPoint {", schema);
            StringAssert.Contains(
                "message SchemaPoint2 {",
                schema,
                "The aliased schema name is renamed."
            );
            Assert.AreEqual(1, diagnostics.Count);
            StringAssert.Contains("already in use", diagnostics[0]);
        }

        [Test]
        public void UnsignedEnumValuesAboveLongMaxRenderInsteadOfThrowing()
        {
            Assert.DoesNotThrow(() =>
                WProtoSchemaText.TryWriteSchema(
                    new[] { typeof(SchemaUnsignedEnumHost) },
                    null,
                    null,
                    out string schema,
                    out IReadOnlyList<string> _
                )
            );

            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaUnsignedEnumHost) },
                null,
                null,
                out string schema,
                out IReadOnlyList<string> diagnostics
            );

            Assert.IsTrue(rendered);
            StringAssert.Contains("Huge = 18446744073709551615;", schema);
            Assert.IsEmpty(diagnostics, "A legal ulong enum member is not an error.");
        }

        [Test]
        public void NonScalarMapKeyBecomesAnEntryMessage()
        {
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaEnumMap) },
                null,
                null,
                out string schema,
                out IReadOnlyList<string> _
            );

            Assert.IsTrue(rendered);
            StringAssert.Contains("map<string, int32> ByString = 1;", schema);
            StringAssert.Contains(
                "message ByColorEntry {\n  SchemaColor key = 1;\n  int32 value = 2;\n}",
                schema,
                "proto3 map keys are scalars only; the wire form is the entry message either way."
            );
            StringAssert.Contains("repeated ByColorEntry ByColor = 2;", schema);
            StringAssert.Contains("enum SchemaColor {", schema);
            StringAssert.Contains("None = 0;", schema);
        }

        [Test]
        public void AListedSubtypeIsNotRenderedTwice()
        {
            // The exporter offers every contract in the assembly, so a polymorphic pair lists the
            // base and the derived type together. The include already rendered the derived
            // message; listing it again must reuse that render, not emit SchemaDerived2.
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaIncludeBase), typeof(SchemaDerived) },
                null,
                null,
                out string schema,
                out IReadOnlyList<string> diagnostics
            );

            Assert.IsTrue(rendered);
            Assert.AreEqual(
                1,
                schema.Split("message SchemaDerived {").Length - 1,
                "The derived message must appear exactly once."
            );
            Assert.IsEmpty(diagnostics);
        }

        [Test]
        public void ASubtypeListedBeforeItsBaseStillRendersOnce()
        {
            // The exporter sorts contracts by C# type name, so a subtype whose name sorts first is
            // the common order in a real export. Whichever order arrives, one message renders and
            // the base references it.
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaDerived), typeof(SchemaIncludeBase) },
                null,
                null,
                out string schema,
                out IReadOnlyList<string> diagnostics
            );

            Assert.IsTrue(rendered);
            Assert.AreEqual(
                1,
                schema.Split("message SchemaDerived {").Length - 1,
                "The derived message must appear exactly once."
            );
            StringAssert.Contains("SchemaDerived schemaDerived = 7;", schema);
            Assert.IsEmpty(diagnostics);
        }

        [Test]
        public void IncludeChainsCarryTheDeeperTagInsideTheShallowerMessage()
        {
            // Base writes Derived under tag 7, and Derived writes SubDerived under tag 8: the
            // wire nests the deeper tag inside the shallower message, so the schema must too.
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaChainBase) },
                null,
                null,
                out string schema,
                out IReadOnlyList<string> diagnostics
            );

            Assert.IsTrue(rendered);
            int derivedIndex = schema.IndexOf(
                "message SchemaChainDerived {",
                StringComparison.Ordinal
            );
            StringAssert.Contains("SchemaChainSubDerived schemaChainSubDerived = 8;", schema);
            StringAssert.Contains("message SchemaChainSubDerived {", schema);
            Assert.Greater(derivedIndex, 0);
            Assert.IsEmpty(diagnostics);
        }

        [Test]
        public void AContractTakingABclShapeNameIsRenamedAndTheShapeStaysValid()
        {
            // The rendered BCL body is built from the final name: if a user contract claimed
            // BclGuid first, the shape must not emit a second message declaring the original
            // name with fields pointing at the new one.
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(BclGuid), typeof(SchemaBcl) },
                null,
                null,
                out string schema,
                out IReadOnlyList<string> diagnostics
            );

            Assert.IsTrue(rendered);
            Assert.AreEqual(
                1,
                schema.Split("message BclGuid {").Length - 1,
                "Exactly one message may declare BclGuid."
            );
            StringAssert.Contains("message BclGuid2 {", schema, "The shape moved to a free name.");
            StringAssert.Contains(
                "BclGuid2 Id = 1;",
                schema,
                "The field follows the renamed shape."
            );
            Assert.AreEqual(1, diagnostics.Count);
            StringAssert.Contains("already in use", diagnostics[0]);
        }

        [Test]
        public void EnumMemberNamesThatCollideAtFileScopeAreRenamedWithADiagnostic()
        {
            // proto3 enum values live in the file's namespace, so two enums that both declare None
            // are not a valid file until the second one is renamed.
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaFirstEnumHost), typeof(SchemaSecondEnumHost) },
                null,
                null,
                out string schema,
                out IReadOnlyList<string> diagnostics
            );

            Assert.IsTrue(rendered);
            StringAssert.Contains("None = 0;", schema);
            StringAssert.Contains(
                "None2 = 0;",
                schema,
                "The second enum's None moves to a free name."
            );
            Assert.AreEqual(1, diagnostics.Count);
            StringAssert.Contains("already in use", diagnostics[0]);
        }

        [Test]
        public void IncludesEmitTheSubtypeWithItsMembersAheadOfTheBase()
        {
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaIncludeBase) },
                null,
                null,
                out string schema,
                out IReadOnlyList<string> diagnostics
            );

            Assert.IsTrue(rendered);
            StringAssert.Contains("int32 Extra = 10;", schema);
            StringAssert.Contains("int32 BaseId = 1;", schema);
            StringAssert.Contains("string BaseName = 2;", schema);
            StringAssert.Contains("SchemaDerived schemaDerived = 7;", schema);
            StringAssert.Contains(
                "// Subtype tag 7 carries the whole SchemaDerived message on the wire.",
                schema
            );
            int derivedIndex = schema.IndexOf("message SchemaDerived {", StringComparison.Ordinal);
            Assert.Greater(derivedIndex, 0, "The include renders the subtype as its own message.");
            Assert.IsEmpty(diagnostics);
        }

        /// <summary>
        /// A subtype that declares itself renders exactly as one the base declares.
        /// </summary>
        /// <remarks>
        /// <para>
        /// The two hierarchies are member for member and tag for tag identical, so once the names
        /// are mapped onto each other the schemas have to be the same text -- the exporter must not
        /// describe the same wire two ways according to where the annotation was written. A
        /// consumer who switches form should see no diff in a generated file they commit.
        /// </para>
        /// <para>
        /// Message ORDER is part of that text, and it is asserted separately as well as through the
        /// whole-text compare, because the whole-text compare reports a reordering as a wall of
        /// unified diff rather than as the one sentence that identifies it.
        /// </para>
        /// </remarks>
        [Test]
        public void ASelfDeclaredSubtypeRendersExactlyAsADeclaredIncludeDoes()
        {
            Assert.IsTrue(
                WProtoSchemaText.TryWriteSchema(
                    new[] { typeof(SchemaIncludeBase) },
                    null,
                    null,
                    out string fromInclude,
                    out IReadOnlyList<string> includeDiagnostics
                )
            );
            Assert.IsTrue(
                WProtoSchemaText.TryWriteSchema(
                    new[] { typeof(SchemaSelfDeclaredRoot) },
                    null,
                    null,
                    out string fromSubtype,
                    out IReadOnlyList<string> subtypeDiagnostics
                )
            );

            string renamed = fromSubtype
                .Replace("SchemaSelfDeclaredDerived", "SchemaDerived")
                .Replace("schemaSelfDeclaredDerived", "schemaDerived")
                .Replace("SchemaSelfDeclaredRoot", "SchemaIncludeBase");

            CollectionAssert.AreEqual(
                MessageOrderOf(fromInclude),
                MessageOrderOf(renamed),
                "The two declaration forms must emit the same messages in the same order."
            );
            Assert.AreEqual(fromInclude, renamed);
            Assert.IsEmpty(includeDiagnostics);
            Assert.IsEmpty(subtypeDiagnostics);
        }

        /// <summary>
        /// The message names of a schema, in the order they are declared.
        /// </summary>
        /// <param name="schema">The rendered schema.</param>
        /// <returns>Each message name, in emission order.</returns>
        private static List<string> MessageOrderOf(string schema)
        {
            List<string> names = new List<string>();
            foreach (string line in schema.Split('\n'))
            {
                string trimmed = line.Trim();
                if (trimmed.StartsWith("message ", StringComparison.Ordinal))
                {
                    names.Add(trimmed.Substring("message ".Length).TrimEnd(' ', '{'));
                }
            }

            return names;
        }

        [Test]
        public void ASelfDeclaredSubtypeIsRenderedEvenWhenOnlyItsBaseIsListed()
        {
            // A base carries no reference to a subtype that declares itself, so nothing on the
            // rendered type leads to it: the exporter has to find the declaration. Missing it would
            // emit a schema that silently omits a field the wire really carries.
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaSelfDeclaredRoot) },
                null,
                null,
                out string schema,
                out IReadOnlyList<string> diagnostics
            );

            Assert.IsTrue(rendered);
            StringAssert.Contains(
                "SchemaSelfDeclaredDerived schemaSelfDeclaredDerived = 7;",
                schema
            );
            StringAssert.Contains("message SchemaSelfDeclaredDerived {", schema);
            StringAssert.Contains("int32 Extra = 10;", schema);
            Assert.AreEqual(
                1,
                schema.Split("message SchemaSelfDeclaredDerived {").Length - 1,
                "The derived message must appear exactly once."
            );
            Assert.IsEmpty(diagnostics);
        }

        [Test]
        public void EnumOdditiesAreReportedRatherThanSilentlyRendered()
        {
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaEnumHost) },
                null,
                null,
                out string schema,
                out IReadOnlyList<string> diagnostics
            );

            Assert.IsTrue(rendered);
            StringAssert.Contains(
                "option allow_alias = true;",
                schema,
                "Aliased enum values need the proto3 option."
            );
            Assert.AreEqual(
                1,
                diagnostics.Count,
                "Only the missing zero reports; aliases are handled."
            );
            StringAssert.Contains("opens at 1", diagnostics[0]);
        }

        [Test]
        public void RenderingTheSameInputTwiceIsDeterministic()
        {
            bool firstRendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaCollections), typeof(SchemaScalars) },
                "demo",
                null,
                out string first,
                out IReadOnlyList<string> _
            );
            bool secondRendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(SchemaCollections), typeof(SchemaScalars) },
                "demo",
                null,
                out string second,
                out IReadOnlyList<string> _
            );

            Assert.IsTrue(firstRendered);
            Assert.IsTrue(secondRendered);
            Assert.AreEqual(
                first,
                second,
                "A schema a consumer diffs must not shuffle between runs."
            );
        }

        [Test]
        public void NonContractAndGenericTypeInputsAreIgnored()
        {
            bool rendered = WProtoSchemaText.TryWriteSchema(
                new[] { typeof(string), typeof(Action<>) },
                null,
                null,
                out string schema,
                out IReadOnlyList<string> _
            );

            Assert.IsFalse(rendered, "Nothing renderable means no schema.");
            Assert.IsTrue(schema == null);
        }
    }

    [WProtoContract]
    public sealed partial class SchemaPoint
    {
        [WProtoMember(1)]
        public int X;

        [WProtoMember(2)]
        public int Y;
    }

    [WProtoContract]
    public sealed partial class SchemaScalars
    {
        [WProtoMember(1, DataFormat = WProtoDataFormat.ZigZag)]
        public long ZigZagValue;

        [WProtoMember(2)]
        public int Signed;

        [WProtoMember(3)]
        public uint Unsigned;

        [WProtoMember(4)]
        public double DoubleValue;

        [WProtoMember(5)]
        public float FloatValue;

        [WProtoMember(6)]
        public string Name;

        [WProtoMember(7)]
        public byte[] Payload;

        [WProtoMember(8)]
        public char Initial;

        [WProtoMember(9)]
        public bool Flag;

        [WProtoMember(10)]
        public int? Maybe;
    }

    [WProtoContract]
    public sealed partial class SchemaBcl
    {
        [WProtoMember(1)]
        public Guid Id;

        [WProtoMember(2)]
        public DateTime Moment;

        [WProtoMember(3)]
        public TimeSpan Duration;

        [WProtoMember(4)]
        public decimal Amount;

        [WProtoMember(5)]
        public Uri Source;
    }

    [WProtoContract]
    public sealed partial class SchemaCollections
    {
        [WProtoMember(1)]
        public int[][] Rows;

        [WProtoMember(2)]
        public byte[][] Blobs;

        [WProtoMember(3)]
        public int[,] Grid;

        [WProtoMember(4)]
        public Dictionary<string, int> Counts;

        [WProtoMember(5)]
        public List<SchemaPoint> Points;
    }

    [WProtoContract]
    public sealed partial class SchemaJaggedOfRectangular
    {
        [WProtoMember(1)]
        public int[][,] Rects;
    }

    public sealed class SchemaForeignVector
    {
        public float X;
        public float Y;
        public float Z;
    }

    [WProtoContract]
    public sealed partial class SchemaForeignVectorSurrogate
    {
        [WProtoMember(1)]
        public float X;

        [WProtoMember(2)]
        public float Y;

        [WProtoMember(3)]
        public float Z;

        public static implicit operator SchemaForeignVectorSurrogate(SchemaForeignVector vector)
        {
            return new SchemaForeignVectorSurrogate
            {
                X = vector.X,
                Y = vector.Y,
                Z = vector.Z,
            };
        }

        public static implicit operator SchemaForeignVector(SchemaForeignVectorSurrogate surrogate)
        {
            return new SchemaForeignVector
            {
                X = surrogate.X,
                Y = surrogate.Y,
                Z = surrogate.Z,
            };
        }
    }

    [WProtoContract]
    public sealed partial class SchemaSurrogateHost
    {
        [WProtoMember(1)]
        public SchemaForeignVector Position;
    }

    [WProtoContract(Name = "SchemaPoint")]
    public sealed partial class SchemaPointAlias
    {
        [WProtoMember(1)]
        public int X;
    }

    public enum SchemaUnsignedColor : ulong
    {
        None = 0,
        Red = 1,
        Huge = 18446744073709551615,
    }

    [WProtoContract]
    public sealed partial class SchemaUnsignedEnumHost
    {
        [WProtoMember(1)]
        public SchemaUnsignedColor Value;
    }

    public enum SchemaColor
    {
        None = 0,
        Red = 1,
        Blue = 2,
    }

    [WProtoContract]
    public sealed partial class SchemaEnumMap
    {
        [WProtoMember(1)]
        public Dictionary<string, int> ByString;

        [WProtoMember(2)]
        public Dictionary<SchemaColor, int> ByColor;
    }

    [WProtoContract]
    [WProtoInclude(7, typeof(SchemaDerived))]
    public partial class SchemaIncludeBase
    {
        [WProtoMember(1)]
        public int BaseId;

        [WProtoMember(2)]
        public string BaseName;
    }

    [WProtoContract]
    public sealed partial class SchemaDerived : SchemaIncludeBase
    {
        [WProtoMember(10)]
        public int Extra;
    }

    // The twin of SchemaIncludeBase/SchemaDerived, declared from the subtype instead. The names
    // are not arbitrary: Render orders messages alphabetically, so "Derived" has to sort before
    // "Root" here exactly as "SchemaDerived" sorts before "SchemaIncludeBase" there. Naming the
    // pair the other way round makes a comparison of the two schemas measure the sort rather than
    // the declaration form -- which is what an earlier version of this fixture did, and it read as
    // an ordering bug in the feature.
    [WProtoContract]
    public partial class SchemaSelfDeclaredRoot
    {
        [WProtoMember(1)]
        public int BaseId;

        [WProtoMember(2)]
        public string BaseName;
    }

    [WProtoContract]
    [WProtoSubtype(typeof(SchemaSelfDeclaredRoot), 7)]
    public sealed partial class SchemaSelfDeclaredDerived : SchemaSelfDeclaredRoot
    {
        [WProtoMember(10)]
        public int Extra;
    }

    [WProtoContract]
    [WProtoInclude(8, typeof(SchemaChainSubDerived))]
    public partial class SchemaChainDerived : SchemaChainBase
    {
        [WProtoMember(10)]
        public int Middle;
    }

    [WProtoContract]
    public sealed partial class SchemaChainSubDerived : SchemaChainDerived
    {
        [WProtoMember(20)]
        public int Leaf;
    }

    [WProtoContract]
    [WProtoInclude(7, typeof(SchemaChainDerived))]
    public partial class SchemaChainBase
    {
        [WProtoMember(1)]
        public int RootId;
    }

    [WProtoContract]
    public sealed partial class BclGuid
    {
        [WProtoMember(1)]
        public int X;
    }

    public enum SchemaFirstEnum
    {
        None = 0,
        First = 1,
    }

    [WProtoContract]
    public sealed partial class SchemaFirstEnumHost
    {
        [WProtoMember(1)]
        public SchemaFirstEnum Value;
    }

    public enum SchemaSecondEnum
    {
        None = 0,
        Second = 2,
    }

    [WProtoContract]
    public sealed partial class SchemaSecondEnumHost
    {
        [WProtoMember(1)]
        public SchemaSecondEnum Value;
    }

    public enum SchemaAliased
    {
        First = 1,
        Prime = 1,
        Second = 2,
    }

    [WProtoContract]
    public sealed partial class SchemaEnumHost
    {
        [WProtoMember(1)]
        public SchemaAliased Value;
    }

    [WProtoContract]
    [WProtoReserved(2, 7)]
    [WProtoReserved("Health", "Armour")]
    public sealed partial class SchemaReserved
    {
        [WProtoMember(1)]
        public int Kept;
    }

    [WProtoContract]
    [WProtoReserved(0, 19500, 536870912)]
    public sealed partial class SchemaReservedOutOfRange
    {
        [WProtoMember(1)]
        public int Kept;
    }

    /// <summary>
    /// An enum that has outlived a member, standing in for the #609 hazard.
    /// </summary>
    /// <remarks>
    /// The reservations cover the two things a deletion frees: the value 3, which is what an older
    /// payload literally carries, and the name it went by, which is what anything matching by name
    /// still looks for. Zero and a negative are reserved as well, because an enum value is any
    /// int32 and the message range would have dropped both.
    /// </remarks>
    [WProtoReserved(3, 0, -2)]
    [WProtoReserved("Poisoned")]
    public enum SchemaReservedEnum
    {
        Unspecified = 1,
        Burning = 2,
    }

    [WProtoContract]
    public sealed partial class SchemaReservedEnumHost
    {
        [WProtoMember(1)]
        public SchemaReservedEnum State;
    }
}
