#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
local_env_file="${repo_root}/.env.local"

if [[ -f "$local_env_file" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$local_env_file"
  set +a
fi

default_host="${UNITY_MCP_DEFAULT_HOST:-192.168.1.33}"
default_port="${UNITY_MCP_DEFAULT_PORT:-9003}"
default_path="${UNITY_MCP_DEFAULT_PATH:-/mcp}"

# Positional args take precedence over env vars (consistent with
# probe-unity-mcp-endpoint.sh), falling back to env, then defaults.
host="${1:-${UNITY_MCP_BRIDGE_HOST:-${UNITY_MCP_HOST:-$default_host}}}"
port="${2:-${UNITY_MCP_BRIDGE_PORT:-${UNITY_MCP_PORT:-$default_port}}}"
endpoint_path="${3:-${UNITY_MCP_BRIDGE_PATH:-${UNITY_MCP_PATH:-$default_path}}}"

if ! command -v node >/dev/null 2>&1; then
  echo "node is required but was not found on PATH." >&2
  exit 1
fi

if [[ ! "$port" =~ ^[0-9]+$ ]] || (( port < 1 || port > 65535 )); then
  echo "UNITY MCP port must be an integer between 1 and 65535. Got: $port" >&2
  exit 1
fi

if [[ "$endpoint_path" != /* ]]; then
  endpoint_path="/$endpoint_path"
fi

UNITY_MCP_HOST="$host" \
UNITY_MCP_PORT="$port" \
UNITY_MCP_PATH="$endpoint_path" \
REPO_ROOT="$repo_root" \
node <<'EOF'
const fs = require('node:fs');
const path = require('node:path');

const repoRoot = process.env.REPO_ROOT;
const host = process.env.UNITY_MCP_HOST;
const port = process.env.UNITY_MCP_PORT;
const endpointPath = process.env.UNITY_MCP_PATH;
const url = `http://${host}:${port}${endpointPath}`;

function toTomlString(value) {
  return String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function ensureParentDir(filePath) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

function writeJson(filePath, value) {
  ensureParentDir(filePath);
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

function readJsonOrDefault(filePath, fallbackValue) {
  if (!fs.existsSync(filePath)) {
    return fallbackValue;
  }

  const raw = fs.readFileSync(filePath, 'utf8').trim();
  if (raw.length === 0) {
    return fallbackValue;
  }

  try {
    return JSON.parse(raw);
  } catch (error) {
    throw new Error(`Invalid JSON in ${filePath}: ${error.message}`);
  }
}

function asObject(value) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    return {};
  }

  return value;
}

function updateJsonUrl(filePath, serverKey) {
  const json = asObject(readJsonOrDefault(filePath, {}));

  const servers = asObject(json[serverKey]);
  json[serverKey] = servers;

  const unityServer = asObject(servers['unity-mcp-remote']);
  servers['unity-mcp-remote'] = unityServer;

  unityServer.type = 'http';
  unityServer.url = url;

  writeJson(filePath, json);
}

function updateCodexUrl(filePath) {
  const tomlUrl = toTomlString(url);
  const codexBlock = [
    '[mcp_servers.unity_mcp_remote]',
    `url = "${tomlUrl}"`,
    'startup_timeout_sec = 20',
    'tool_timeout_sec = 120',
    'enabled = true',
    '',
  ].join('\n');

  if (!fs.existsSync(filePath)) {
    const initial = [
      '# Machine-local Codex MCP config generated by scripts/mcp/configure-unity-mcp-endpoint.sh.',
      '# This file is gitignored. Re-run the script when host/port/path changes.',
      '',
      codexBlock,
    ].join('\n');

    ensureParentDir(filePath);
    fs.writeFileSync(filePath, initial, 'utf8');
    return;
  }

  const codexRaw = fs.readFileSync(filePath, 'utf8');
  const codexPattern = /(\[mcp_servers\.unity_mcp_remote\][\s\S]*?^url\s*=\s*").*?(")/m;

  if (codexPattern.test(codexRaw)) {
    const codexNext = codexRaw.replace(codexPattern, (match, prefix, suffix) => `${prefix}${tomlUrl}${suffix}`);
    if (codexNext !== codexRaw) {
      fs.writeFileSync(filePath, codexNext, 'utf8');
    }
    return;
  }

  const appended = `${codexRaw.replace(/\s*$/, '')}\n\n${codexBlock}`;
  fs.writeFileSync(filePath, appended, 'utf8');
}

updateJsonUrl(path.join(repoRoot, '.vscode', 'mcp.json'), 'servers');
updateJsonUrl(path.join(repoRoot, '.mcp.json'), 'mcpServers');
updateJsonUrl(path.join(repoRoot, '.cursor', 'mcp.json'), 'mcpServers');
updateCodexUrl(path.join(repoRoot, '.codex', 'config.toml'));

console.log(`Updated Unity MCP endpoint to ${url}`);
EOF

echo "Configured bridge endpoint for workspace clients: http://${host}:${port}${endpoint_path}"
