// MIT License - Copyright (c) 2026 wallstop
// Full license text: https://github.com/wallstop/unity-helpers/blob/main/LICENSE

namespace WallstopStudios.UnityHelpers.Core.Serialization.WallstopProto
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Globalization;
    using System.Linq;
    using System.Reflection;
    using System.Text;

    /// <summary>
    /// Renders the wire contract of <see cref="WProtoContractAttribute"/> types as a proto3 schema a
    /// downstream consumer can read with any protobuf toolchain.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Every declaration emitted here is chosen to be byte-exact with what the formatters write:
    /// scalars map to their wire types, jagged collections map to the same wrapper messages the
    /// source generator synthesizes, rectangular arrays map to the <c>dims</c>/<c>values</c> wrapper
    /// from <see cref="WProtoRectangular"/>, maps map to proto3 <c>map</c> entries (or an explicit
    /// entry message where the key has no proto3 spelling), and a
    /// <see cref="WProtoIncludeAttribute"/> subtype is emitted as a message holding the subtype's
    /// members followed by the base's, exactly as the wire lays the bytes out. The BCL value types
    /// the formatters serve (<see cref="DateTime"/>, <see cref="TimeSpan"/>, <see cref="Guid"/>,
    /// <see cref="decimal"/>, <see cref="Uri"/>) are emitted as the message shapes those formatters
    /// actually write, which replicate protobuf-net's <c>.bcl.*</c> conventions.
    /// </para>
    /// <para>
    /// Two writer behaviors have no proto3 spelling and are deliberately not reflected in the
    /// schema: <see cref="WProtoMemberAttribute.IsRequired"/>, which changes only whether a default
    /// value is written, and the never-packed rule for <see cref="char"/> runs, which changes only
    /// whether runs are compressed. Neither changes a field's number or type, so a schema consumer
    /// decodes both correctly without knowing them.
    /// </para>
    /// <para>
    /// Nothing here throws on a shape it cannot express. An unsupported member is skipped and
    /// reported through the returned diagnostics, so the rest of the schema stays usable; a caller
    /// that requires every member represented checks that the diagnostics list is empty.
    /// </para>
    /// </remarks>
    public static class WProtoSchemaText
    {
        private const string Header =
            "// Generated by Wallstop Studios Unity Helpers. Do not edit; regenerate instead.\n"
            + "syntax = \"proto3\";\n";

        /// <summary>
        /// The BCL value types this toolchain serves on the wire, mapped to the message shapes the
        /// formatters actually write. Each body is built from the final message name, because the
        /// name is reserved on arrival and renamed with a diagnostic when taken.
        /// </summary>
        private static readonly Dictionary<
            Type,
            (string MessageName, Func<string, string> BuildDefinition)
        > BclMessageShapes = new Dictionary<Type, (string, Func<string, string>)>
        {
            {
                typeof(DateTime),
                (
                    "BclDateTime",
                    name =>
                        "// Replicates protobuf-net's .bcl.DateTime layout.\n"
                        + "message "
                        + name
                        + " {\n"
                        + "  sint64 value = 1;\n"
                        + "  uint32 scale = 2;\n"
                        + "}"
                )
            },
            {
                typeof(TimeSpan),
                (
                    "BclTimeSpan",
                    name =>
                        "// Replicates protobuf-net's .bcl.TimeSpan layout.\n"
                        + "message "
                        + name
                        + " {\n"
                        + "  sint64 value = 1;\n"
                        + "  uint32 scale = 2;\n"
                        + "}"
                )
            },
            {
                typeof(Guid),
                (
                    "BclGuid",
                    name =>
                        "// Replicates protobuf-net's .bcl.Guid layout: two fixed-64 halves in\n"
                        + "// Guid.ToByteArray order; an all-zero Guid writes an empty message.\n"
                        + "message "
                        + name
                        + " {\n"
                        + "  fixed64 low = 1;\n"
                        + "  fixed64 high = 2;\n"
                        + "}"
                )
            },
            {
                typeof(decimal),
                (
                    "BclDecimal",
                    name =>
                        "// Replicates protobuf-net's .bcl.Decimal layout.\n"
                        + "message "
                        + name
                        + " {\n"
                        + "  uint64 low = 1;\n"
                        + "  uint32 high = 2;\n"
                        + "  uint32 sign_scale = 3;\n"
                        + "}"
                )
            },
            {
                typeof(Uri),
                (
                    "BclUri",
                    name =>
                        "// Replicates protobuf-net's .bcl.Uri layout: the UTF-8 original string.\n"
                        + "message "
                        + name
                        + " {\n"
                        + "  string original_string = 1;\n"
                        + "}"
                )
            },
        };

        /// <summary>
        /// The types this toolchain refuses to place on the wire, with the recorded reason.
        /// </summary>
        private static readonly Dictionary<Type, string> RefusedTypes = new Dictionary<Type, string>
        {
            {
                typeof(DateTimeOffset),
                "neither supported protobuf-net version provides any wire shape for it"
            },
            { typeof(IntPtr), "platform-width pointer; protobuf-net 2.x has no serializer for it" },
            {
                typeof(UIntPtr),
                "platform-width pointer; protobuf-net 2.x has no serializer for it"
            },
            { typeof(Type), "bytes name a runtime-bound type another process cannot resolve" },
        };

        /// <summary>
        /// Renders a proto3 schema for the given contract types.
        /// </summary>
        /// <param name="contractTypes">
        /// The <see cref="WProtoContractAttribute"/> types to render. Types without the attribute are
        /// ignored; types referenced as members render only when listed here or reached through an
        /// include or an element mapping.
        /// </param>
        /// <param name="packageName">The proto package clause, or <c>null</c> to omit it.</param>
        /// <param name="surrogates">
        /// The <see cref="WProtoSurrogateAttribute"/> pairs to honor, keyed by the real type.
        /// Members whose type is replaced by a surrogate render as the surrogate's message.
        /// </param>
        /// <param name="schema">The rendered schema, or <c>null</c> when nothing was rendered.</param>
        /// <param name="diagnostics">
        /// Every skipped member and naming adjustment the caller may need to act on. Empty when the
        /// schema expresses every member of every rendered contract.
        /// </param>
        /// <returns><c>true</c> when at least one contract was rendered.</returns>
        public static bool TryWriteSchema(
            IEnumerable<Type> contractTypes,
            string packageName,
            IReadOnlyDictionary<Type, Type> surrogates,
            out string schema,
            out IReadOnlyList<string> diagnostics
        )
        {
            if (contractTypes == null)
            {
                schema = null;
                diagnostics = Array.Empty<string>();
                return false;
            }

            List<Type> requested = new List<Type>();
            foreach (Type contractType in contractTypes)
            {
                if (contractType == null || contractType.IsGenericTypeDefinition)
                {
                    continue;
                }

                requested.Add(contractType);
            }

            SchemaBuilder builder = new SchemaBuilder(surrogates, BuildSubtypeIndex(requested));
            foreach (Type contractType in requested)
            {
                builder.TryAddContract(contractType);
            }

            if (builder.MessageCount == 0)
            {
                schema = null;
                diagnostics = Array.Empty<string>();
                return false;
            }

            schema = builder.Render(packageName);
            diagnostics = builder.Diagnostics.ToArray();
            return true;
        }

        /// <summary>
        /// Indexes every <see cref="WProtoSubtypeAttribute"/> declaration reachable from the
        /// requested contracts, keyed by the base each one names.
        /// </summary>
        /// <param name="requested">The contracts the caller asked to render.</param>
        /// <returns>Each base's declared subtypes, ordered by field number.</returns>
        /// <remarks>
        /// <para>
        /// A subtype declares itself, so the base carries no reference to follow and the
        /// declarations have to be found rather than read off the type being rendered. Scanning the
        /// assemblies the requested contracts came from is what makes the two declaration forms
        /// produce the same schema from the same selection: an <see cref="WProtoIncludeAttribute"/>
        /// subtype is rendered whether or not the caller listed it, and this one now is too.
        /// </para>
        /// <para>
        /// The direct-base check is the same rule the generator enforces, and it is also what makes
        /// the walk terminate: a declaration naming anything other than the type's immediate base
        /// -- itself included -- is not indexed, so no chain of subtype messages can cycle.
        /// </para>
        /// </remarks>
        private static Dictionary<Type, List<KeyValuePair<int, Type>>> BuildSubtypeIndex(
            List<Type> requested
        )
        {
            Dictionary<Type, List<KeyValuePair<int, Type>>> index =
                new Dictionary<Type, List<KeyValuePair<int, Type>>>();
            HashSet<Assembly> assemblies = new HashSet<Assembly>();
            List<Type> candidates = new List<Type>(requested);
            foreach (Type contractType in requested)
            {
                if (assemblies.Add(contractType.Assembly))
                {
                    candidates.AddRange(TypesOf(contractType.Assembly));
                }
            }

            HashSet<Type> visited = new HashSet<Type>();
            foreach (Type candidate in candidates)
            {
                if (candidate == null || !visited.Add(candidate))
                {
                    continue;
                }

                if (!candidate.IsDefined(typeof(WProtoSubtypeAttribute), false))
                {
                    continue;
                }

                foreach (
                    object markerObject in candidate.GetCustomAttributes(
                        typeof(WProtoSubtypeAttribute),
                        false
                    )
                )
                {
                    WProtoSubtypeAttribute marker = (WProtoSubtypeAttribute)markerObject;
                    if (marker.BaseType == null || marker.BaseType != candidate.BaseType)
                    {
                        continue;
                    }

                    if (
                        !index.TryGetValue(
                            marker.BaseType,
                            out List<KeyValuePair<int, Type>> declared
                        )
                    )
                    {
                        declared = new List<KeyValuePair<int, Type>>();
                        index[marker.BaseType] = declared;
                    }

                    declared.Add(new KeyValuePair<int, Type>(marker.Tag, candidate));
                }
            }

            foreach (List<KeyValuePair<int, Type>> declared in index.Values)
            {
                declared.Sort(CompareDeclarations);
            }

            return index;
        }

        private static int CompareDeclarations(
            KeyValuePair<int, Type> left,
            KeyValuePair<int, Type> right
        )
        {
            int byTag = left.Key.CompareTo(right.Key);
            return byTag != 0
                ? byTag
                : string.CompareOrdinal(left.Value.FullName, right.Value.FullName);
        }

        /// <summary>
        /// The types of one assembly, or as many of them as loaded.
        /// </summary>
        /// <param name="assembly">The assembly to enumerate.</param>
        /// <returns>The loadable types; empty when none can be read.</returns>
        /// <remarks>
        /// A partially loadable assembly is ordinary in an editor with a broken or absent optional
        /// dependency, and the schema of the types that DID load is still worth rendering.
        /// </remarks>
        private static IEnumerable<Type> TypesOf(Assembly assembly)
        {
            try
            {
                return assembly.GetTypes();
            }
            catch (ReflectionTypeLoadException loadFailure)
            {
                return loadFailure.Types ?? Array.Empty<Type>();
            }
            catch (Exception)
            {
                return Array.Empty<Type>();
            }
        }

        private sealed class SchemaBuilder
        {
            private const BindingFlags MemberSearchFlags =
                BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic;
            private const string MessageKeyPrefix = "message ";
            private const string EnumKeyPrefix = "enum ";

            private readonly IReadOnlyDictionary<Type, Type> _surrogates;
            private readonly Dictionary<Type, List<KeyValuePair<int, Type>>> _declaredSubtypes;
            private readonly List<string> _diagnostics = new List<string>();
            private readonly Dictionary<string, string> _blocks = new Dictionary<string, string>(
                StringComparer.Ordinal
            );
            private readonly HashSet<Type> _rendered = new HashSet<Type>();
            private readonly HashSet<string> _usedNames = new HashSet<string>(
                StringComparer.Ordinal
            );
            private readonly Dictionary<Type, string> _contractNames =
                new Dictionary<Type, string>();
            private readonly Dictionary<Type, string> _bclNames = new Dictionary<Type, string>();
            private readonly Dictionary<Type, string> _enumNames = new Dictionary<Type, string>();

            public SchemaBuilder(
                IReadOnlyDictionary<Type, Type> surrogates,
                Dictionary<Type, List<KeyValuePair<int, Type>>> declaredSubtypes
            )
            {
                _surrogates = surrogates ?? new Dictionary<Type, Type>();
                _declaredSubtypes = declaredSubtypes;
            }

            public List<string> Diagnostics => _diagnostics;

            public int MessageCount => _rendered.Count;

            public string TryAddContract(Type contractType)
            {
                if (_rendered.Contains(contractType))
                {
                    return SchemaNameOf(contractType);
                }

                object[] contractMarkers = contractType.GetCustomAttributes(
                    typeof(WProtoContractAttribute),
                    false
                );
                if (contractMarkers.Length == 0)
                {
                    return null;
                }

                _rendered.Add(contractType);
                string messageName = SchemaIdentifierFor(
                    ResolveSchemaName(contractType, (WProtoContractAttribute)contractMarkers[0]),
                    contractType.Name
                );
                _contractNames[contractType] = messageName;

                List<IncludeEntry> includes = CollectIncludes(contractType);
                List<MemberEntry> members = CollectMembers(contractType, messageName);
                StringBuilder body = new StringBuilder();
                body.Append("message ").Append(messageName).Append(" {").Append("\n");
                AppendReserved(contractType, messageName, body, false);
                foreach (MemberEntry member in members)
                {
                    string line = RenderField(messageName, member);
                    if (line != null)
                    {
                        body.Append("  ").Append(line).Append("\n");
                    }
                }

                foreach (IncludeEntry include in includes)
                {
                    body.Append("  // Subtype tag ")
                        .Append(include.Tag.ToString(CultureInfo.InvariantCulture))
                        .Append(" carries the whole ")
                        .Append(include.SchemaName)
                        .Append(" message on the wire.")
                        .Append("\n");
                    body.Append("  ")
                        .Append(include.SchemaName)
                        .Append(' ')
                        .Append(FieldName(include.SchemaName))
                        .Append(" = ")
                        .Append(include.Tag.ToString(CultureInfo.InvariantCulture))
                        .Append(";")
                        .Append("\n");
                }

                body.Append("}");
                _blocks[MessageKeyPrefix + messageName] = body.ToString();
                return messageName;
            }

            /// <summary>
            /// Writes the contract's <c>[WProtoReserved]</c> declarations as proto3 reservations.
            /// </summary>
            /// <param name="contractType">The contract or enum being rendered.</param>
            /// <param name="messageName">Its schema name, for diagnostics.</param>
            /// <param name="body">The message or enum body being built.</param>
            /// <param name="forEnum">
            /// Whether the block is an <c>enum</c>, which reserves over a different range than a
            /// message does.
            /// </param>
            /// <remarks>
            /// <para>
            /// Without these the exported schema permits, in the consumer's own toolchain, exactly
            /// the reuse the generator refuses here -- so a removed member's number would come back
            /// meaning something else one build system over.
            /// </para>
            /// <para>
            /// A message reserves FIELD numbers and an enum reserves VALUES, and the two ranges are
            /// not the same: a field number is 1..536870911 with protoc's own 19000-19999 carved
            /// out, while an enum value is any int32 -- 0 and negatives included. Filtering an enum
            /// through the message range would drop a perfectly legal reservation of 0, and silently
            /// (<see href="https://github.com/Ambiguous-Interactive/unity-helpers/issues/609">#609</see>).
            /// </para>
            /// </remarks>
            private void AppendReserved(
                Type contractType,
                string messageName,
                StringBuilder body,
                bool forEnum
            )
            {
                object[] markers = contractType.GetCustomAttributes(
                    typeof(WProtoReservedAttribute),
                    false
                );
                if (markers.Length == 0)
                {
                    return;
                }

                SortedSet<int> numbers = new SortedSet<int>();
                SortedSet<string> names = new SortedSet<string>(StringComparer.Ordinal);
                foreach (object marker in markers)
                {
                    WProtoReservedAttribute reserved = marker as WProtoReservedAttribute;
                    if (reserved == null)
                    {
                        continue;
                    }

                    foreach (int number in reserved.FieldNumbers)
                    {
                        /*
                            A number proto3 could not have used is not a number this schema can
                            reserve: protoc rejects both ends of the range and owns 19000-19999
                            itself, so emitting one would make the whole file impossible to parse.
                        */
                        if (
                            forEnum
                            || (
                                1 <= number
                                && number <= 536870911
                                && (number < 19000 || 19999 < number)
                            )
                        )
                        {
                            numbers.Add(number);
                        }
                        else
                        {
                            _diagnostics.Add(
                                $"{messageName}: reserved field number {number.ToString(CultureInfo.InvariantCulture)} is outside the range proto3 allows; omitted."
                            );
                        }
                    }

                    foreach (string name in reserved.MemberNames)
                    {
                        if (!string.IsNullOrEmpty(name) && IsValidProtoIdentifier(name))
                        {
                            names.Add(name);
                        }
                        else
                        {
                            _diagnostics.Add(
                                $"{messageName}: reserved name '{name}' is not a valid proto3 identifier; omitted."
                            );
                        }
                    }
                }

                if (0 < numbers.Count)
                {
                    body.Append("  reserved ");
                    bool first = true;
                    foreach (int number in numbers)
                    {
                        if (!first)
                        {
                            body.Append(", ");
                        }

                        body.Append(number.ToString(CultureInfo.InvariantCulture));
                        first = false;
                    }

                    body.Append(";").Append("\n");
                }

                if (0 < names.Count)
                {
                    body.Append("  reserved ");
                    bool first = true;
                    foreach (string name in names)
                    {
                        if (!first)
                        {
                            body.Append(", ");
                        }

                        body.Append('"').Append(name).Append('"');
                        first = false;
                    }

                    body.Append(";").Append("\n");
                }
            }

            private string RenderField(string ownerName, MemberEntry member)
            {
                Type memberType = member.MemberType;

                if (RefusedTypes.TryGetValue(memberType, out string refusal))
                {
                    _diagnostics.Add(
                        $"{ownerName}.{member.SchemaName}: {memberType.Name} refused -- {refusal}; skipped."
                    );
                    return null;
                }

                if (
                    memberType.IsGenericType
                    && memberType.GetGenericTypeDefinition() == typeof(Nullable<>)
                )
                {
                    Type underlying = memberType.GetGenericArguments()[0];
                    if (!TryMapElement(underlying, member, out string nullableType))
                    {
                        _diagnostics.Add(
                            $"{ownerName}.{member.SchemaName}: Nullable<{underlying.Name}> of an unsupported element skipped."
                        );
                        return null;
                    }

                    return $"optional {nullableType} {member.SchemaName} = {member.Tag};";
                }

                if (TryMapScalar(memberType, member, out string scalarType))
                {
                    return $"{scalarType} {member.SchemaName} = {member.Tag};";
                }

                if (memberType == typeof(byte[]))
                {
                    return $"bytes {member.SchemaName} = {member.Tag};";
                }

                if (memberType.IsEnum)
                {
                    string enumName = TryAddEnum(memberType);
                    return enumName == null
                        ? null
                        : $"{enumName} {member.SchemaName} = {member.Tag};";
                }

                if (memberType.IsArray && 1 < memberType.GetArrayRank())
                {
                    /*
                        A rectangular array travels as the dims/values wrapper; see WProtoRectangular
                        for the read-side shape validation.
                    */
                    Type elementType = memberType.GetElementType();
                    string rectName = NextName(member.SchemaName + "Rect");
                    if (
                        !TryBuildRectBody(
                            rectName,
                            elementType,
                            ownerName,
                            out string rectDefinition
                        )
                    )
                    {
                        return null;
                    }

                    _blocks[MessageKeyPrefix + rectName] = rectDefinition;
                    return $"{rectName} {member.SchemaName} = {member.Tag};";
                }

                if (TryResolveSurrogate(memberType, out Type surrogateType))
                {
                    string surrogateName = TryAddContract(surrogateType);
                    if (surrogateName != null)
                    {
                        return $"{surrogateName} {member.SchemaName} = {member.Tag};";
                    }
                }

                object[] contractMarkers = memberType.GetCustomAttributes(
                    typeof(WProtoContractAttribute),
                    false
                );
                if (0 < contractMarkers.Length)
                {
                    string contractName = TryAddContract(memberType);
                    return $"{contractName} {member.SchemaName} = {member.Tag};";
                }

                if (TryShapeRepeated(memberType, member, ownerName, out string repeatedType))
                {
                    return $"repeated {repeatedType} {member.SchemaName} = {member.Tag};";
                }

                _diagnostics.Add(
                    $"{ownerName}.{member.SchemaName}: {memberType.Name} has no WProto contract and no supported wire shape; skipped."
                );
                return null;
            }

            private bool TryShapeRepeated(
                Type memberType,
                MemberEntry member,
                string ownerName,
                out string repeatedType
            )
            {
                if (memberType.IsGenericType && IsMapDictionary(memberType))
                {
                    return TryBuildMap(memberType, member, ownerName, out repeatedType);
                }

                Type elementType = GetElementType(memberType);
                if (elementType == null)
                {
                    repeatedType = null;
                    return false;
                }

                return TryMapRepeatedElement(elementType, member, ownerName, out repeatedType);
            }

            private bool TryMapRepeatedElement(
                Type elementType,
                MemberEntry scope,
                string ownerName,
                out string protoType
            )
            {
                if (TryResolveSurrogate(elementType, out Type surrogateType))
                {
                    string surrogateName = TryAddContract(surrogateType);
                    if (surrogateName == null)
                    {
                        protoType = null;
                        return false;
                    }

                    protoType = surrogateName;
                    return true;
                }

                if (elementType.IsEnum)
                {
                    protoType = TryAddEnum(elementType);
                    return protoType != null;
                }

                if (elementType == typeof(byte[]))
                {
                    /*
                        A byte[] is a bytes scalar rather than a run of its own, so byte[][] is an
                        ordinary repeated field, not a wrapper -- the same call the generator makes.
                    */
                    protoType = "bytes";
                    return true;
                }

                if (elementType.IsArray && 1 < elementType.GetArrayRank())
                {
                    /*
                        A rectangular array nested anywhere gets the dims/values wrapper, exactly as
                        the generator gives one to a top-level member: the dimensions have to travel
                        with the elements or the shape is lost.
                    */
                    string rectName = NextName(scope.SchemaName + "Rect");
                    if (
                        !TryBuildRectBody(
                            rectName,
                            elementType.GetElementType(),
                            ownerName,
                            out string rectDefinition
                        )
                    )
                    {
                        protoType = null;
                        return false;
                    }

                    _blocks[MessageKeyPrefix + rectName] = rectDefinition;
                    protoType = rectName;
                    return true;
                }

                if (elementType.IsArray || IsCollection(elementType))
                {
                    /*
                        A jagged collection has no proto spelling, so each inner run gets the same
                        wrapper message the source generator synthesizes: a repeated wrapper at the
                        member tag, the inner run at field one.
                    */
                    Type innerElement = GetElementType(elementType);
                    if (innerElement == null)
                    {
                        protoType = null;
                        return false;
                    }

                    string wrapperName = NextName(scope.SchemaName + "Entry");
                    MemberEntry innerScope = new MemberEntry
                    {
                        SchemaName = "values",
                        Tag = 1,
                        MemberType = innerElement,
                    };
                    if (
                        !TryMapRepeatedElement(
                            innerElement,
                            innerScope,
                            ownerName,
                            out string innerType
                        )
                    )
                    {
                        protoType = null;
                        return false;
                    }

                    StringBuilder wrapper = new StringBuilder();
                    wrapper.Append("message ").Append(wrapperName).Append(" {").Append("\n");
                    wrapper
                        .Append("  repeated ")
                        .Append(innerType)
                        .Append(" values = 1;")
                        .Append("\n");
                    wrapper.Append("}");
                    _blocks[MessageKeyPrefix + wrapperName] = wrapper.ToString();
                    protoType = wrapperName;
                    return true;
                }

                if (TryMapScalar(elementType, scope, out protoType))
                {
                    return true;
                }

                return TryMapContract(elementType, out protoType);
            }

            private bool TryMapContract(Type type, out string protoType)
            {
                object[] markers = type.GetCustomAttributes(typeof(WProtoContractAttribute), false);
                if (markers.Length == 0)
                {
                    protoType = null;
                    return false;
                }

                protoType = TryAddContract(type);
                return protoType != null;
            }

            private bool TryBuildRectBody(
                string rectName,
                Type elementType,
                string ownerName,
                out string definition
            )
            {
                MemberEntry elementScope = new MemberEntry
                {
                    SchemaName = "values",
                    Tag = 2,
                    MemberType = elementType,
                };

                if (
                    !TryMapRepeatedElement(
                        elementType,
                        elementScope,
                        ownerName,
                        out string valuesType
                    )
                )
                {
                    _diagnostics.Add(
                        $"{ownerName}: rectangular element {elementType.Name} has no supported wire shape; skipped."
                    );
                    definition = null;
                    return false;
                }

                StringBuilder rect = new StringBuilder();
                rect.Append("// Rectangular-array wrapper; see WProtoRectangular: the dimension")
                    .Append("\n");
                rect.Append("// product must equal the delivered element count.").Append("\n");
                rect.Append("message ").Append(rectName).Append(" {").Append("\n");
                rect.Append("  repeated int32 dims = 1;").Append("\n");
                rect.Append("  repeated ").Append(valuesType).Append(" values = 2;").Append("\n");
                rect.Append("}");
                definition = rect.ToString();
                return true;
            }

            private bool TryBuildMap(
                Type memberType,
                MemberEntry member,
                string ownerName,
                out string line
            )
            {
                Type[] arguments = memberType.GetGenericArguments();
                Type keyType = arguments[0];
                Type valueType = arguments[1];

                if (!TryMapElement(keyType, member, out string keyProtoType))
                {
                    _diagnostics.Add(
                        $"{ownerName}.{member.SchemaName}: map key {keyType.Name} has no proto3 spelling; skipped."
                    );
                    line = null;
                    return false;
                }

                if (!TryMapElement(valueType, member, out string valueProtoType))
                {
                    _diagnostics.Add(
                        $"{ownerName}.{member.SchemaName}: map value {valueType.Name} has no supported wire shape; skipped."
                    );
                    line = null;
                    return false;
                }

                if (IsProto3MapKey(keyProtoType))
                {
                    line = $"map<{keyProtoType}, {valueProtoType}>";
                    return true;
                }

                /*
                    proto3 map keys are restricted to integral, boolean and string scalars; the wire
                    form is a repeated entry message either way, so emit exactly that.
                */
                string entryName = NextName(member.SchemaName + "Entry");
                StringBuilder entry = new StringBuilder();
                entry.Append("message ").Append(entryName).Append(" {").Append("\n");
                entry.Append("  ").Append(keyProtoType).Append(" key = 1;").Append("\n");
                entry.Append("  ").Append(valueProtoType).Append(" value = 2;").Append("\n");
                entry.Append("}");
                _blocks[MessageKeyPrefix + entryName] = entry.ToString();
                line = entryName;
                return true;
            }

            private string TryAddEnum(Type enumType)
            {
                if (_enumNames.TryGetValue(enumType, out string known))
                {
                    return known;
                }

                string enumName = SchemaIdentifierFor(enumType.Name, $"enum {enumType.Name}");
                if (enumName == null)
                {
                    return null;
                }

                _enumNames[enumType] = enumName;

                string blockKey = EnumKeyPrefix + enumName;
                if (_blocks.ContainsKey(blockKey))
                {
                    return enumName;
                }

                Array values = Enum.GetValues(enumType);
                string[] names = Enum.GetNames(enumType);
                if (values.Length == 0)
                {
                    _diagnostics.Add($"enum {enumType.Name}: declares no members; skipped.");
                    return null;
                }

                bool unsigned =
                    Enum.GetUnderlyingType(enumType) == typeof(ulong)
                    || Enum.GetUnderlyingType(enumType) == typeof(uint)
                    || Enum.GetUnderlyingType(enumType) == typeof(ushort)
                    || Enum.GetUnderlyingType(enumType) == typeof(byte);

                bool aliases = false;
                List<KeyValuePair<string, string>> declared = new List<
                    KeyValuePair<string, string>
                >(values.Length);
                HashSet<string> seen = new HashSet<string>(StringComparer.Ordinal);
                for (int i = 0; i < values.Length; ++i)
                {
                    /*
                        An unsigned enum may legally hold a value above long.MaxValue; rendering
                        through signed conversion would throw, so the underlying width decides.
                    */
                    string raw = unsigned
                        ? Convert
                            .ToUInt64(values.GetValue(i), CultureInfo.InvariantCulture)
                            .ToString(CultureInfo.InvariantCulture)
                        : Convert
                            .ToInt64(values.GetValue(i), CultureInfo.InvariantCulture)
                            .ToString(CultureInfo.InvariantCulture);
                    if (!seen.Add(raw))
                    {
                        aliases = true;
                    }

                    declared.Add(new KeyValuePair<string, string>(names[i], raw));
                }

                if (declared[0].Value != "0")
                {
                    _diagnostics.Add(
                        $"enum {enumType.Name}: proto3 wants the first member at 0; it opens at {declared[0].Value}."
                    );
                }

                StringBuilder body = new StringBuilder();
                body.Append("enum ").Append(enumName).Append(" {").Append("\n");
                if (aliases)
                {
                    body.Append("  option allow_alias = true;").Append("\n");
                }

                /*
                    Same reservation syntax proto3 uses for a message, and needed for the same
                    reason: without it a consumer's own toolchain would permit exactly the value
                    reuse WPROTO046 refuses here.
                */
                AppendReserved(enumType, enumName, body, true);

                foreach (KeyValuePair<string, string> member in declared)
                {
                    /*
                        Proto3 enum values share the file's namespace with messages and every other
                        enum's values, so each member name is validated and reserved like a type's.
                    */
                    string memberName = SchemaIdentifierFor(
                        member.Key,
                        $"enum {enumType.Name}.{member.Key}"
                    );
                    body.Append("  ")
                        .Append(memberName)
                        .Append(" = ")
                        .Append(member.Value)
                        .Append(";")
                        .Append("\n");
                }

                body.Append("}");
                string definition = body.ToString();
                _blocks[blockKey] = definition;
                return enumName;
            }

            /// <summary>
            /// Validates a type-derived name as a proto3 identifier, renaming with a diagnostic when
            /// it is not one -- a closed generic arrives as <c>Box`1</c>, which no proto file accepts.
            /// </summary>
            private string SchemaIdentifierFor(string desired, string context)
            {
                bool collision =
                    _usedNames.Contains(desired)
                    || _blocks.ContainsKey(MessageKeyPrefix + desired)
                    || _blocks.ContainsKey(EnumKeyPrefix + desired);
                if (collision)
                {
                    string renamed = NextName(
                        IsValidProtoIdentifier(desired) ? desired : SanitizeIdentifier(desired)
                    );
                    _diagnostics.Add(
                        $"{context}: the name {desired} is already in use; renamed to {renamed}."
                    );
                    return renamed;
                }

                if (IsValidProtoIdentifier(desired))
                {
                    return NextName(desired);
                }

                string cleaned = SanitizeIdentifier(desired);
                string candidate = NextName(cleaned);
                _diagnostics.Add(
                    $"{context}: {desired} is not a valid proto3 identifier; renamed to {candidate}."
                );
                return candidate;
            }

            private static string SanitizeIdentifier(string desired)
            {
                StringBuilder builder = new StringBuilder(desired.Length);
                foreach (char character in desired)
                {
                    if (IsAsciiIdentifierCharacter(character))
                    {
                        builder.Append(character);
                    }
                }

                if (builder.Length == 0 || char.IsDigit(builder[0]))
                {
                    builder.Insert(0, '_');
                }

                return builder.ToString();
            }

            /// <summary>
            /// Every subtype of one contract, however it was declared, ordered by field number.
            /// </summary>
            /// <param name="contractType">The contract whose subtypes are wanted.</param>
            /// <returns>The rendered include fields.</returns>
            /// <remarks>
            /// <c>[WProtoInclude(tag, typeof(Sub))]</c> on the base and
            /// <c>[WProtoSubtype(typeof(Base), tag)]</c> on the subtype are one declaration written
            /// from either end, so they merge into one list and the field-number order makes the two
            /// forms render the same text. A field number claimed twice is a build error the
            /// generator reports; here it is a diagnostic and a skip, because a schema is worth
            /// rendering for the rest of a contract that has one.
            /// </remarks>
            private List<IncludeEntry> CollectIncludes(Type contractType)
            {
                List<KeyValuePair<int, Type>> declarations = new List<KeyValuePair<int, Type>>();
                object[] markers = contractType.GetCustomAttributes(
                    typeof(WProtoIncludeAttribute),
                    false
                );
                foreach (object markerObject in markers)
                {
                    WProtoIncludeAttribute marker = (WProtoIncludeAttribute)markerObject;
                    Type derived = marker.KnownType;
                    if (derived == null)
                    {
                        _diagnostics.Add(
                            $"WProtoInclude at tag {marker.Tag} on {contractType.Name} names no type; skipped."
                        );
                        continue;
                    }

                    declarations.Add(new KeyValuePair<int, Type>(marker.Tag, derived));
                }

                if (
                    _declaredSubtypes != null
                    && _declaredSubtypes.TryGetValue(
                        contractType,
                        out List<KeyValuePair<int, Type>> fromSubtypes
                    )
                )
                {
                    declarations.AddRange(fromSubtypes);
                }

                declarations.Sort(CompareDeclarations);

                List<IncludeEntry> includes = new List<IncludeEntry>();
                HashSet<int> claimed = new HashSet<int>();
                foreach (KeyValuePair<int, Type> declaration in declarations)
                {
                    if (!claimed.Add(declaration.Key))
                    {
                        _diagnostics.Add(
                            $"{contractType.Name}: subtype {declaration.Value.Name} claims field number {declaration.Key}, which another subtype already took; skipped."
                        );
                        continue;
                    }

                    string derivedName = EnsureDerivedMessage(declaration.Value);
                    includes.Add(
                        new IncludeEntry { Tag = declaration.Key, SchemaName = derivedName }
                    );
                }

                return includes;
            }

            /// <summary>
            /// Renders a subtype's message once, whoever asks for it: a base's include, the
            /// subtype's own listing as a contract, a second base sharing the subtype, or a chain.
            /// The body carries the subtype's members -- <see cref="CollectMembers"/> walks the
            /// hierarchy, so that includes the base's -- followed by the subtype's own include
            /// fields, because a chain writes the deeper tag inside the shallower message.
            /// </summary>
            private string EnsureDerivedMessage(Type derived)
            {
                if (
                    _rendered.Contains(derived)
                    && _contractNames.TryGetValue(derived, out string known)
                )
                {
                    return known;
                }

                string derivedName = SchemaIdentifierFor(
                    ResolveContractName(derived),
                    derived.Name
                );
                _rendered.Add(derived);
                _contractNames[derived] = derivedName;

                StringBuilder body = new StringBuilder();
                body.Append("message ").Append(derivedName).Append(" {").Append("\n");
                foreach (MemberEntry member in CollectMembers(derived, derivedName))
                {
                    string line = RenderField(derivedName, member);
                    if (line != null)
                    {
                        body.Append("  ").Append(line).Append("\n");
                    }
                }

                foreach (IncludeEntry nested in CollectIncludes(derived))
                {
                    body.Append("  // Subtype tag ")
                        .Append(nested.Tag.ToString(CultureInfo.InvariantCulture))
                        .Append(" carries the whole ")
                        .Append(nested.SchemaName)
                        .Append(" message on the wire.")
                        .Append("\n");
                    body.Append("  ")
                        .Append(nested.SchemaName)
                        .Append(' ')
                        .Append(FieldName(nested.SchemaName))
                        .Append(" = ")
                        .Append(nested.Tag.ToString(CultureInfo.InvariantCulture))
                        .Append(";")
                        .Append("\n");
                }

                body.Append("}");
                _blocks[MessageKeyPrefix + derivedName] = body.ToString();
                return derivedName;
            }

            private List<MemberEntry> CollectMembers(Type contractType, string messageName)
            {
                List<MemberEntry> members = new List<MemberEntry>();
                for (
                    Type current = contractType;
                    current != null && current != typeof(object);
                    current = current.BaseType
                )
                {
                    AppendDeclaredMembers(current, messageName, members);
                }

                List<MemberEntry> unique = new List<MemberEntry>(members.Count);
                HashSet<int> seenTags = new HashSet<int>();
                foreach (MemberEntry member in members)
                {
                    if (!seenTags.Add(member.Tag))
                    {
                        continue;
                    }

                    unique.Add(member);
                }

                unique.Sort((left, right) => left.Tag.CompareTo(right.Tag));
                return unique;
            }

            private void AppendDeclaredMembers(
                Type declaredType,
                string messageName,
                List<MemberEntry> into
            )
            {
                IEnumerable<MemberEntry> fields = declaredType
                    .GetFields(MemberSearchFlags)
                    .Select(member => BuildMember(member, messageName))
                    .Where(entry => entry != null);
                IEnumerable<MemberEntry> properties = declaredType
                    .GetProperties(MemberSearchFlags)
                    .Select(member => BuildMember(member, messageName))
                    .Where(entry => entry != null);

                into.AddRange(fields);
                into.AddRange(properties);
            }

            private MemberEntry BuildMember(MemberInfo member, string messageName)
            {
                object[] markers = member.GetCustomAttributes(typeof(WProtoMemberAttribute), false);
                if (markers.Length == 0)
                {
                    return null;
                }

                WProtoMemberAttribute marker = (WProtoMemberAttribute)markers[0];
                Type memberType;
                if (member is FieldInfo field)
                {
                    memberType = field.FieldType;
                }
                else
                {
                    memberType = ((PropertyInfo)member).PropertyType;
                }

                string schemaName = string.IsNullOrEmpty(marker.Name) ? member.Name : marker.Name;
                if (!IsValidProtoIdentifier(schemaName))
                {
                    _diagnostics.Add(
                        $"{messageName}.{schemaName}: not a valid proto3 identifier; renamed to field_{marker.Tag}."
                    );
                    schemaName = "field_" + marker.Tag.ToString(CultureInfo.InvariantCulture);
                }

                return new MemberEntry
                {
                    SchemaName = schemaName,
                    Tag = marker.Tag,
                    MemberType = memberType,
                    DataFormatZigZag = marker.DataFormat == WProtoDataFormat.ZigZag,
                };
            }

            private bool TryResolveSurrogate(Type type, out Type surrogateType)
            {
                return _surrogates.TryGetValue(type, out surrogateType) && surrogateType != null;
            }

            private string SchemaNameOf(Type contractType)
            {
                if (
                    _contractNames.TryGetValue(contractType, out string rendered)
                    && rendered != null
                )
                {
                    return rendered;
                }

                return ResolveContractName(contractType);
            }

            private string ResolveSchemaName(Type type, WProtoContractAttribute marker)
            {
                return string.IsNullOrEmpty(marker.Name) ? ResolveContractName(type) : marker.Name;
            }

            private static string ResolveContractName(Type type)
            {
                object[] markers = type.GetCustomAttributes(typeof(WProtoContractAttribute), false);
                if (0 < markers.Length)
                {
                    string declared = ((WProtoContractAttribute)markers[0]).Name;
                    if (!string.IsNullOrEmpty(declared))
                    {
                        return declared;
                    }
                }

                return type.Name;
            }

            private string NextName(string desired)
            {
                string candidate = desired;
                int suffix = 2;
                while (
                    _usedNames.Contains(candidate)
                    || _blocks.ContainsKey(MessageKeyPrefix + candidate)
                    || _blocks.ContainsKey(EnumKeyPrefix + candidate)
                )
                {
                    candidate = desired + suffix.ToString(CultureInfo.InvariantCulture);
                    ++suffix;
                }

                _usedNames.Add(candidate);
                return candidate;
            }

            public string Render(string packageName)
            {
                StringBuilder schema = new StringBuilder();
                schema.Append(Header);
                if (!string.IsNullOrWhiteSpace(packageName))
                {
                    schema.Append("package ").Append(packageName.Trim()).Append(";").Append("\n");
                }

                schema.Append("\n");
                foreach (
                    KeyValuePair<string, string> block in _blocks.OrderBy(
                        pair => pair.Key,
                        StringComparer.Ordinal
                    )
                )
                {
                    schema.Append(block.Value).Append("\n");
                    schema.Append("\n");
                }

                return schema.ToString();
            }

            private bool TryMapScalar(Type type, MemberEntry member, out string protoType)
            {
                protoType = MapScalarName(type, member);
                return protoType != null;
            }

            private string MapScalarName(Type type, MemberEntry member)
            {
                bool zigZag = member.DataFormatZigZag;
                if (type == typeof(bool))
                {
                    return "bool";
                }

                if (type == typeof(sbyte))
                {
                    return zigZag ? "sint32" : "int32";
                }

                if (type == typeof(short))
                {
                    return zigZag ? "sint32" : "int32";
                }

                if (type == typeof(int))
                {
                    return zigZag ? "sint32" : "int32";
                }

                if (type == typeof(long))
                {
                    return zigZag ? "sint64" : "int64";
                }

                if (type == typeof(byte))
                {
                    return "uint32";
                }

                if (type == typeof(ushort))
                {
                    return "uint32";
                }

                if (type == typeof(uint))
                {
                    return "uint32";
                }

                if (type == typeof(ulong))
                {
                    return "uint64";
                }

                if (type == typeof(char))
                {
                    return "uint32";
                }

                if (type == typeof(float))
                {
                    return "fixed32";
                }

                if (type == typeof(double))
                {
                    return "fixed64";
                }

                if (type == typeof(string))
                {
                    return "string";
                }

                if (
                    BclMessageShapes.TryGetValue(
                        type,
                        out (string MessageName, Func<string, string> BuildDefinition) shape
                    )
                )
                {
                    if (_bclNames.TryGetValue(type, out string assigned))
                    {
                        return assigned;
                    }

                    string name = SchemaIdentifierFor(
                        shape.MessageName,
                        $"the wire shape for {type.Name}"
                    );
                    _bclNames[type] = name;
                    _blocks[MessageKeyPrefix + name] = shape.BuildDefinition(name);
                    return name;
                }

                return null;
            }

            private bool TryMapElement(Type type, MemberEntry member, out string protoType)
            {
                if (TryResolveSurrogate(type, out Type surrogateType))
                {
                    string surrogateName = TryAddContract(surrogateType);
                    if (surrogateName == null)
                    {
                        protoType = null;
                        return false;
                    }

                    protoType = surrogateName;
                    return true;
                }

                if (type.IsEnum)
                {
                    protoType = TryAddEnum(type);
                    return protoType != null;
                }

                if (TryMapScalar(type, member, out protoType))
                {
                    return true;
                }

                return TryMapContract(type, out protoType);
            }

            private static Type GetElementType(Type type)
            {
                if (type.IsArray)
                {
                    return type.GetElementType();
                }

                if (type.IsGenericType)
                {
                    Type definition = type.GetGenericTypeDefinition();
                    if (definition == typeof(IEnumerable<>))
                    {
                        return type.GetGenericArguments()[0];
                    }
                }

                foreach (Type implemented in type.GetInterfaces())
                {
                    if (
                        implemented.IsGenericType
                        && implemented.GetGenericTypeDefinition() == typeof(IEnumerable<>)
                    )
                    {
                        return implemented.GetGenericArguments()[0];
                    }
                }

                return null;
            }

            private static bool IsCollection(Type type)
            {
                if (type == typeof(string) || type == typeof(byte[]))
                {
                    return false;
                }

                if (
                    type.IsArray
                    || (
                        type.IsGenericType
                        && type.GetGenericTypeDefinition() == typeof(IEnumerable<>)
                    )
                )
                {
                    return true;
                }

                foreach (Type implemented in type.GetInterfaces())
                {
                    if (
                        implemented.IsGenericType
                        && implemented.GetGenericTypeDefinition() == typeof(IEnumerable<>)
                    )
                    {
                        return true;
                    }
                }

                return false;
            }

            private static bool IsMapDictionary(Type type)
            {
                Type definition = type.GetGenericTypeDefinition();
                return definition == typeof(Dictionary<,>)
                    || definition == typeof(IDictionary<,>)
                    || definition == typeof(IReadOnlyDictionary<,>)
                    || definition == typeof(ReadOnlyDictionary<,>);
            }

            private static bool IsProto3MapKey(string protoType)
            {
                switch (protoType)
                {
                    case "bool":
                    case "int32":
                    case "int64":
                    case "uint32":
                    case "uint64":
                    case "sint32":
                    case "sint64":
                    case "fixed32":
                    case "fixed64":
                    case "string":
                        return true;
                    default:
                        return false;
                }
            }

            private static bool IsValidProtoIdentifier(string name)
            {
                if (string.IsNullOrEmpty(name))
                {
                    return false;
                }

                if (!IsAsciiIdentifierCharacter(name[0]) || char.IsDigit(name[0]))
                {
                    return false;
                }

                for (int i = 1; i < name.Length; ++i)
                {
                    if (!IsAsciiIdentifierCharacter(name[i]))
                    {
                        return false;
                    }
                }

                return true;
            }

            private static bool IsAsciiIdentifierCharacter(char character)
            {
                return ('a' <= character && character <= 'z')
                    || ('A' <= character && character <= 'Z')
                    || ('0' <= character && character <= '9')
                    || character == '_';
            }

            private static string FieldName(string messageName)
            {
                return char.ToLowerInvariant(messageName[0]) + messageName.Substring(1);
            }
        }

        private sealed class IncludeEntry
        {
            public int Tag;
            public string SchemaName;
        }

        private sealed class MemberEntry
        {
            public string SchemaName;
            public int Tag;
            public Type MemberType;
            public bool DataFormatZigZag;
        }
    }
}
