<#
.SYNOPSIS
    Fails a non-doc comment that spans more than one line and is not written in block form.

.DESCRIPTION
    `.llm/context.md` rule 8: a non-doc comment inside a type or member spanning more than one
    line uses block form. Runtime, Editor, Tests and Generator~ are fully enforced, with no
    baseline exemptions. Delete narration before converting retained rationale.

    Comment spans come from `scripts/comment-stripping.ps1`'s `Get-CommentRanges`, which already
    knows a `//` inside a string literal is not a comment and tells `XmlDoc` apart from
    `LineComment`. A second scanner here would be a second answer to one question.

    Depth comes from indentation rather than brace counting, which CSharpier guarantees: a namespace
    body is indented four, a type body eight. So a run indented eight or more is inside a type or a
    member, and the file-level license header and namespace-level comments are outside the rule by
    construction.
#>
[CmdletBinding(PositionalBinding = $false)]
Param(
    [string[]]$Paths = @(),
    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]]$RemainingPaths = @(),
    [string]$RepoRoot = '',
    [switch]$Fix,
    [switch]$VerboseOutput
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

. (Join-Path -Path $PSScriptRoot -ChildPath 'comment-stripping.ps1')

$usingFixtureRoot = -not [string]::IsNullOrWhiteSpace($RepoRoot)
$repoRoot = if ($usingFixtureRoot) { (Get-Item $RepoRoot).FullName } else { (Get-Item $PSScriptRoot).Parent.FullName }
$roots = @('Runtime', 'Editor', 'Tests', 'Generator~')

# Vendored upstream verbatim, so its comments are not this repository's to restyle -- the same
# exclusion lint:comparison-direction carries.
$excludedPrefixes = @('Runtime/Utils/SevenZip/')

# A run made only of directives is not prose and has no block form: a tool reads each line.
$directivePattern = '^//\s*(UNH-SUPPRESS|cspell:|ReSharper|resharper|Justification:|<auto-generated)'

function Get-TargetFiles {
    param([string[]]$Requested)

    if ($Requested.Count -gt 0) {
        return @($Requested | Where-Object { $_ -like '*.cs' } | Sort-Object -Unique)
    }

    if ($usingFixtureRoot) {
        $found = New-Object System.Collections.Generic.List[string]
        foreach ($root in $roots) {
            $directory = Join-Path -Path $repoRoot -ChildPath $root
            if (-not (Test-Path -LiteralPath $directory -PathType Container)) {
                continue
            }
            foreach ($file in (Get-ChildItem -LiteralPath $directory -Recurse -Filter '*.cs' -File)) {
                $relative = $file.FullName.Substring($repoRoot.Length + 1)
                $found.Add(($relative -replace '\\', '/')) | Out-Null
            }
        }
        return @($found)
    }

    Push-Location $repoRoot
    try {
        return @(& git ls-files --cached --others --exclude-standard -- 'Runtime/*.cs' 'Editor/*.cs' 'Tests/*.cs' 'Generator~/*.cs')
    }
    finally {
        Pop-Location
    }
}

function Get-Violations {
    param(
        [string]$RelativePath,
        [string]$Text
    )

    $found = New-Object System.Collections.Generic.List[object]
    $ranges = Get-CommentRanges -Text $Text -Language 'csharp'
    if ($ranges.Count -eq 0) {
        return $found
    }

    $lineStarts = New-Object System.Collections.Generic.List[int]
    $lineStarts.Add(0) | Out-Null
    for ($index = 0; $index -lt $Text.Length; $index++) {
        if ($Text[$index] -eq "`n") {
            $lineStarts.Add($index + 1) | Out-Null
        }
    }

    $standalone = New-Object System.Collections.Generic.List[object]
    $searchFrom = 0
    foreach ($range in $ranges) {
        if ($range.Kind -ne 'LineComment') {
            continue
        }

        while (($searchFrom + 1) -lt $lineStarts.Count -and $lineStarts[$searchFrom + 1] -le $range.Start) {
            $searchFrom++
        }

        $lineStart = $lineStarts[$searchFrom]
        $prefix = $Text.Substring($lineStart, $range.Start - $lineStart)
        if ($prefix.Trim().Length -gt 0) {
            # A trailing comment on a code line is one comment on that line, not part of a run.
            continue
        }

        $standalone.Add([pscustomobject]@{
                Line   = $searchFrom + 1
                Indent = $prefix.Length
                Text   = $Text.Substring($range.Start, $range.End - $range.Start).TrimEnd("`r")
            }) | Out-Null
    }

    $runStart = 0
    while ($runStart -lt $standalone.Count) {
        $runEnd = $runStart
        while (($runEnd + 1) -lt $standalone.Count -and
            $standalone[$runEnd + 1].Line -eq ($standalone[$runEnd].Line + 1)) {
            $runEnd++
        }

        $length = $runEnd - $runStart + 1
        if ($length -ge 2) {
            $insideType = $true
            $allDirectives = $true
            for ($index = $runStart; $index -le $runEnd; $index++) {
                if ($standalone[$index].Indent -lt 8) {
                    $insideType = $false
                }
                if ($standalone[$index].Text -notmatch $directivePattern) {
                    $allDirectives = $false
                }
            }

            if ($insideType -and -not $allDirectives) {
                $body = New-Object System.Collections.Generic.List[string]
                $closesBlock = $false
                for ($index = $runStart; $index -le $runEnd; $index++) {
                    $stripped = $standalone[$index].Text.Substring(2)
                    if ($stripped.StartsWith(' ')) {
                        $stripped = $stripped.Substring(1)
                    }
                    if ($stripped.Contains('*/') -or $stripped.Contains('/*')) {
                        $closesBlock = $true
                    }
                    $body.Add($stripped) | Out-Null
                }

                $found.Add([pscustomobject]@{
                        File       = $RelativePath
                        Line       = $standalone[$runStart].Line
                        EndLine    = $standalone[$runEnd].Line
                        Lines      = $length
                        Indent     = $standalone[$runStart].Indent
                        Body       = $body
                        Convertible = -not $closesBlock
                        First      = $standalone[$runStart].Text.Substring(0, [Math]::Min(70, $standalone[$runStart].Text.Length))
                    }) | Out-Null
            }
        }

        $runStart = $runEnd + 1
    }

    return $found
}

$requested = @($Paths) + @($RemainingPaths)
$targets = Get-TargetFiles -Requested $requested
$scanned = @{}
foreach ($root in $roots) {
    $scanned[$root] = 0
}

$violations = New-Object System.Collections.Generic.List[object]
$unreadable = New-Object System.Collections.Generic.List[string]
foreach ($relative in $targets) {
    $full = Join-Path -Path $repoRoot -ChildPath $relative
    if (-not (Test-Path -LiteralPath $full -PathType Leaf)) {
        continue
    }

    $normalized = ($relative -replace '\\', '/')
    $excluded = $false
    foreach ($prefix in $excludedPrefixes) {
        if ($normalized.StartsWith($prefix)) {
            $excluded = $true
        }
    }
    if ($excluded) {
        continue
    }

    foreach ($root in $roots) {
        if ($normalized.StartsWith("$root/")) {
            $scanned[$root]++
        }
    }

    $text = ''
    try {
        $text = [System.IO.File]::ReadAllText($full)
    }
    catch {
        # A file that could not be read is a hole in the measurement, not a clean result.
        $unreadable.Add("${normalized}: $($_.Exception.Message)") | Out-Null
        continue
    }

    foreach ($violation in (Get-Violations -RelativePath $normalized -Text $text)) {
        $violations.Add($violation) | Out-Null
    }
}

if ($unreadable.Count -gt 0) {
    Write-Host '[lint-comment-block-form] Files could not be read:' -ForegroundColor Red
    foreach ($entry in $unreadable) {
        Write-Host "  $entry" -ForegroundColor Yellow
    }
    exit 1
}

# A full scan that saw nothing in a root examined nothing there. Skipped for an explicit -Paths run,
# which is scoped to whatever the caller passed.
if ($requested.Count -eq 0) {
    foreach ($root in $roots) {
        if ($scanned[$root] -le 0) {
            Write-Host "[lint-comment-block-form] $root/ yielded no C# files, so this run examined nothing there." -ForegroundColor Red
            exit 1
        }
    }
}

if ($Fix) {
    $byFile = @{}
    foreach ($violation in $violations) {
        if (-not $byFile.ContainsKey($violation.File)) {
            $byFile[$violation.File] = New-Object System.Collections.Generic.List[object]
        }
        $byFile[$violation.File].Add($violation) | Out-Null
    }

    $rewritten = 0
    $declined = 0
    foreach ($file in @($byFile.Keys | Sort-Object)) {
        $full = Join-Path -Path $repoRoot -ChildPath $file
        $raw = [System.IO.File]::ReadAllText($full)
        $newline = if ($raw.Contains("`r`n")) { "`r`n" } else { "`n" }
        $lines = [System.Collections.Generic.List[string]]::new(($raw -replace "`r`n", "`n") -split "`n")

        # Latest run first, so an earlier run's line numbers are still correct when it is reached.
        $ordered = @($byFile[$file] | Sort-Object -Property Line -Descending)
        $changed = $false
        foreach ($violation in $ordered) {
            if (-not $violation.Convertible) {
                $declined++
                continue
            }

            $pad = ' ' * $violation.Indent
            $replacement = New-Object System.Collections.Generic.List[string]
            $replacement.Add("$pad/*") | Out-Null
            foreach ($bodyLine in $violation.Body) {
                if ($bodyLine.Trim().Length -eq 0) {
                    $replacement.Add('') | Out-Null
                }
                else {
                    $replacement.Add("$pad    $bodyLine") | Out-Null
                }
            }
            $replacement.Add("$pad*/") | Out-Null

            $lines.RemoveRange($violation.Line - 1, $violation.Lines)
            $lines.InsertRange($violation.Line - 1, $replacement)
            $changed = $true
        }

        if ($changed) {
            [System.IO.File]::WriteAllText($full, ($lines -join $newline), (New-Object System.Text.UTF8Encoding($false)))
            $rewritten++
        }
    }

    Write-Host "[lint-comment-block-form] Rewrote $rewritten file(s); declined $declined run(s) whose text carries a comment delimiter." -ForegroundColor Green
    exit 0
}

if ($violations.Count -gt 0) {
    Write-Host "[lint-comment-block-form] $($violations.Count) multi-line // comment run(s)." -ForegroundColor Red
    Write-Host 'Delete the run, or write it as one /* ... */ block. See .llm/context.md rule 8.' -ForegroundColor Cyan
    foreach ($violation in $violations) {
        Write-Host "  $($violation.File):$($violation.Line)  $($violation.Lines) lines  $($violation.First)" -ForegroundColor Yellow
    }
    exit 1
}

$summary = ($roots | ForEach-Object { "$($_)/ $($scanned[$_])" }) -join ', '
Write-Host "[lint-comment-block-form] Scanned $summary file(s); 0 multi-line // comment runs." -ForegroundColor Green
