name: Publish to NPM

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          lfs: true
          
      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
            
      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          unityVersion: 2022.3.51f1
          testMode: playmode
          artifactsPath: test-results
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: Unity Test Results
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+WallstopStudios.UnityHelpers.*'

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test results
          path: test-results
          
      - name: Upload Coverage Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Coverage results
          path: CodeCoverage

  publish_npm:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Ensure full commit history for version comparison

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'

      - name: Check if version changed
        id: version_check
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Manual trigger detected. Skipping version check."
            NEW_VERSION=$(jq -r '.version' package.json)
            echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
            echo "should_publish=true" >> $GITHUB_ENV
            if [[ "$NEW_VERSION" == *"rc"* ]]; then
              echo "This is a pre-release (next tag)."
              echo "NPM_TAG=next" >> $GITHUB_ENV
            else
              echo "This is a stable release (latest tag)."
              echo "NPM_TAG=latest" >> $GITHUB_ENV
            fi
          else
            PREV_VERSION=$(git show HEAD~1:package.json | jq -r '.version' || echo "0.0.0")
            NEW_VERSION=$(jq -r '.version' package.json)
            echo "Previous version: $PREV_VERSION"
            echo "New version: $NEW_VERSION"

            if [ "$PREV_VERSION" != "$NEW_VERSION" ]; then
              echo "Version changed, proceeding..."
              echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
              echo "should_publish=true" >> $GITHUB_ENV

              # Detect pre-releases (versions with "rc" or similar tags)
              if [[ "$NEW_VERSION" == *"rc"* ]]; then
                echo "This is a pre-release (next tag)."
                echo "NPM_TAG=next" >> $GITHUB_ENV
              else
                echo "This is a stable release (latest tag)."
                echo "NPM_TAG=latest" >> $GITHUB_ENV
              fi
            else
              echo "Version did not change, skipping..."
              echo "should_publish=false" >> $GITHUB_ENV
            fi
          fi

      - name: Install Dependencies
        if: env.should_publish == 'true'
        run: npm install

      - name: Publish to NPM
        if: env.should_publish == 'true'
        run: npm publish --access public --tag ${{ env.NPM_TAG }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
